### PR TITLE
add output smtp v4

### LINKED ISSUE #23: add support for ses_smtp_password_v4
## Describe the Bug

This is primarily an effect from another module that am using ([SES](https://github.com/cloudposse/terraform-aws-ses)), I see there is no way to get the SMTP password using the AWS's SigV4 conversion algorithm. I just noticed this while I was going through the documentation in https://www.terraform.io/docs/providers/aws/r/iam_access_key.html.

```
ses_smtp_password - DEPRECATED The secret access key converted into an SES SMTP password by applying AWS's SigV2 conversion algorithm

ses_smtp_password_v4 - The secret access key converted into an SES SMTP password by applying AWS's documented Sigv4 conversion algorithm. As SigV4 is region specific, valid Provider regions are
```

## Expected Behavior

Include an output such as: **aws_iam_access_key.this.*.ses_smtp_password_v4** to be able to retrieve the password on this endpoint.

### PR DESCRIPTION
**Pull request by korporationcl**
## what
* The current implementation does not have a way to present the smtp password for SES AWS's Sigv4, there is only a deprecated way available.

## why
* current output for getting the SMTP password is officially deprecated. 

## references
* Use `closes #23`, if this PR closes a GitHub issue `#23`

### CODE REVIEW

**Comment by jamengual** [comment]
Thanks for the contribution, could you please delete the output `"ses_smtp_password"` since is now deprecated?

**Comment by korporationcl** [comment]
> Thanks for the contribution, could you please delete the output `"ses_smtp_password"` since is now deprecated?

sure thing!

**Comment by jamengual** [comment]
@korporationcl could you please rebase from master? Thanks.

**Comment by korporationcl** [comment]
Thank you!

**Pull request merged**
